import { createHash, randomUUID } from "node:crypto";
import { CronExpressionParser } from "cron-parser";
import { Redis } from "ioredis";
import { Pool, type PoolConfig } from "pg";
import type { INode, IWorkflow, JsonValue, NodeId, WorkflowId } from "@spiderz/shared";

export interface TriggerExecutionQueue { enqueueTriggeredExecution(workflowId: WorkflowId, input: readonly JsonValue[], idempotencyKey: string): Promise<void>; }
export interface PollingState { readonly cursor: JsonValue | null; readonly lastCheckedAt: string | null; }
export interface PollingStateStore { get(workflowId: WorkflowId, nodeId: NodeId): Promise<PollingState>; save(workflowId: WorkflowId, nodeId: NodeId, state: PollingState): Promise<void>; }
export interface PollingHandler { supports(node: INode): boolean; poll(node: INode, state: PollingState): Promise<{ events: readonly { id: string; data: JsonValue }[]; cursor: JsonValue | null }>; }
export class PostgresPollingStateStore implements PollingStateStore { private readonly pool: Pool; public constructor(config: PoolConfig) { this.pool = new Pool(config); } public async get(workflowId: WorkflowId, nodeId: NodeId): Promise<PollingState> { const r = await this.pool.query<{ cursor: JsonValue | null; last_checked_at: Date | null }>("SELECT cursor,last_checked_at FROM trigger_state WHERE workflow_id=$1 AND node_id=$2", [workflowId, nodeId]); const row = r.rows[0]; return row === undefined ? { cursor: null, lastCheckedAt: null } : { cursor: row.cursor, lastCheckedAt: row.last_checked_at?.toISOString() ?? null }; } public async save(workflowId: WorkflowId, nodeId: NodeId, state: PollingState): Promise<void> { await this.pool.query("INSERT INTO trigger_state(workflow_id,node_id,cursor,last_checked_at) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(workflow_id,node_id) DO UPDATE SET cursor=EXCLUDED.cursor,last_checked_at=EXCLUDED.last_checked_at", [workflowId, nodeId, JSON.stringify(state.cursor), state.lastCheckedAt]); } }
export interface TriggerEngineOptions { queue: TriggerExecutionQueue; redis: Redis; pollingState: PollingStateStore; pollingHandlers: readonly PollingHandler[]; onError?: (error: Error) => void; }
export class TriggerEngine { private readonly timers = new Map<string, ReturnType<typeof setTimeout>>(); public constructor(private readonly options: TriggerEngineOptions) {} public register(workflow: IWorkflow): void { for (const node of workflow.nodes) { if (node.type === "trigger" && node.parameters.triggerKind === "cron") this.scheduleCron(workflow, node); if (node.type === "trigger" && node.parameters.triggerKind === "poll") this.schedulePoll(workflow, node); } } public stop(): void { for (const t of this.timers.values()) clearTimeout(t); this.timers.clear(); }
  private scheduleCron(workflow: IWorkflow, node: INode): void { try { const e = node.parameters.cronExpression; if (typeof e !== "string") throw new Error("Missing cronExpression"); const next = CronExpressionParser.parse(e, { strict: true }).next().toDate(); const k = `${workflow.id}/${node.id}/cron`; this.timers.set(k, setTimeout(() => { void this.fireCron(workflow, node, next).finally(() => this.scheduleCron(workflow, node)); }, Math.min(Math.max(next.getTime() - Date.now(), 0), 2_147_000_000))); } catch (e: unknown) { this.report(e); } }
  private async fireCron(w: IWorkflow, n: INode, at: Date): Promise<void> { const key = this.key("cron", w.id, n.id, at.toISOString()); await this.lock(key, () => this.options.queue.enqueueTriggeredExecution(w.id, [{ trigger: "cron", nodeId: n.id, scheduledAt: at.toISOString() }], key)); }
  private schedulePoll(w: IWorkflow, n: INode): void { const s = n.parameters.pollIntervalSeconds; if (typeof s !== "number" || !Number.isInteger(s) || s < 10) return this.report(new Error("pollIntervalSeconds must be >= 10")); this.timers.set(`${w.id}/${n.id}/poll`, setTimeout(() => { void this.firePoll(w, n).finally(() => this.schedulePoll(w, n)); }, s * 1_000)); }
  private async firePoll(w: IWorkflow, n: INode): Promise<void> { const h = this.options.pollingHandlers.find((x) => x.supports(n)); if (h === undefined) return this.report(new Error(`No polling handler for ${n.id}`)); await this.lock(this.key("poll", w.id, n.id), async () => { const state = await this.options.pollingState.get(w.id, n.id); const r = await h.poll(n, state); for (const event of r.events) { const k = this.key("poll-event", w.id, n.id, event.id); await this.options.queue.enqueueTriggeredExecution(w.id, [{ trigger: "poll", nodeId: n.id, data: event.data }], k); } await this.options.pollingState.save(w.id, n.id, { cursor: r.cursor, lastCheckedAt: new Date().toISOString() }); }); }
  private async lock(key: string, fn: () => Promise<void>): Promise<void> { const token = randomUUID(), name = `trigger-lock:${key}`; if (await this.options.redis.set(name, token, "PX", 120_000, "NX") !== "OK") return; try { await fn(); } finally { await this.options.redis.eval("if redis.call('get',KEYS[1])==ARGV[1] then return redis.call('del',KEYS[1]) end", 1, name, token); } } private key(...p: string[]): string { return createHash("sha256").update(p.join("\0")).digest("hex"); } private report(e: unknown): void { this.options.onError?.(e instanceof Error ? e : new Error(String(e))); } }
