import type { IWorkflow } from "@spiderz/shared"; import { authorizedHeaders } from "./auth.js"; import { currentWorkspaceId } from "./workspace.js";
const API=import.meta.env.VITE_API_BASE_URL??"http://localhost:3000";export const workspaceId=currentWorkspaceId;
export async function workspaces(){const r=await fetch(`${API}/api/workspaces`,{headers:authorizedHeaders()});if(!r.ok)throw Error("Could not load workspaces.");return r.json() as Promise<{id:string;name:string;environment:string;role:string;organization_name:string}[]>;}
export type WorkflowListPage={items:{id:string;name:string;enabled:boolean;updated_at:string;last_execution_status:string|null}[];page:number;pageSize:number;total:number;};
export type WorkflowFilter="all"|"active"|"draft"|"failed"|"owned";
export async function listWorkflows(q="",page=1,filter:WorkflowFilter="all"){const r=await fetch(`${API}/api/workspaces/${workspaceId()}/workflows?q=${encodeURIComponent(q)}&page=${page}&pageSize=20&filter=${filter}`,{headers:authorizedHeaders()});if(!r.ok)throw new Error("Could not load workflows.");return r.json() as Promise<WorkflowListPage>;}
export async function openWorkflow(id:string){const r=await fetch(`${API}/api/workspaces/${workspaceId()}/workflows/${id}`,{headers:authorizedHeaders()});if(!r.ok)throw new Error("Could not open workflow.");return r.json() as Promise<IWorkflow>;}
export async function createWorkflow(){const workflow:IWorkflow={id:crypto.randomUUID(),name:"Untitled workflow",nodes:[],connections:[],settings:{},variables:{}};const r=await fetch(`${API}/api/workspaces/${workspaceId()}/workflows`,{method:"POST",headers:authorizedHeaders(),body:JSON.stringify(workflow)});if(!r.ok)throw new Error("Could not create workflow.");return workflow;}
export async function deleteWorkflow(id:string):Promise<void>{const r=await fetch(`${API}/api/workspaces/${workspaceId()}/workflows/${id}`,{method:"DELETE",headers:authorizedHeaders()});if(!r.ok)throw new Error("Could not delete workflow.");}
export async function setWorkflowEnabled(id:string,enabled:boolean):Promise<void>{const r=await fetch(`${API}/api/workspaces/${workspaceId()}/workflows/${id}/status`,{method:"PATCH",headers:authorizedHeaders(),body:JSON.stringify({enabled})});if(!r.ok)throw new Error("Could not update workflow status.");}
export async function duplicateWorkflow(id:string){const r=await fetch(`${API}/api/workspaces/${workspaceId()}/workflows/${id}/duplicate`,{method:"POST",headers:authorizedHeaders()});if(!r.ok)throw Error("Could not duplicate workflow.");return r.json() as Promise<IWorkflow>;}
