import { createHash, randomBytes } from "node:crypto";
import type { FastifyInstance } from "fastify";
import { Pool, type PoolConfig } from "pg";
import { requireWorkspaceRole, type WorkspaceRole } from "./rbac.js";
export function registerMemberRoutes(app: FastifyInstance, config: PoolConfig): void { const pool = new Pool(config);
  app.get<{ Params: { workspaceId: string } }>("/api/workspaces/:workspaceId/members", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member", "read_only") }, async (r) => (await pool.query("SELECT u.id,u.email,m.role FROM workspace_memberships m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=$1 ORDER BY u.email", [r.params.workspaceId])).rows);
  app.post<{ Params: { workspaceId: string }; Body: { email: string; role: WorkspaceRole } }>("/api/workspaces/:workspaceId/invitations", { preHandler: requireWorkspaceRole(config, "owner", "admin") }, async (r, reply) => { if (!['admin','member','read_only'].includes(r.body.role) || !/^\S+@\S+\.\S+$/.test(r.body.email)) return reply.code(400).send({ error: 'Invalid email or role.' }); const token = randomBytes(32).toString('base64url'); await pool.query("INSERT INTO workspace_invitations(workspace_id,email,role,token_hash,expires_at,invited_by) VALUES($1,$2,$3,$4,now()+interval '7 days',$5) ON CONFLICT(workspace_id,email) DO UPDATE SET role=EXCLUDED.role,token_hash=EXCLUDED.token_hash,expires_at=EXCLUDED.expires_at,accepted_at=NULL", [r.params.workspaceId,r.body.email.toLowerCase(),r.body.role,hash(token),r.user.sub]); return reply.code(201).send({ invitationToken: token, expiresInDays: 7 }); });
  app.post<{ Body: { token: string } }>("/api/invitations/accept", async (r, reply) => { await r.jwtVerify(); const client=await pool.connect(); try { await client.query('BEGIN'); const invite=await client.query<{workspace_id:string;role:WorkspaceRole;email:string}>("SELECT workspace_id,role,email FROM workspace_invitations WHERE token_hash=$1 AND accepted_at IS NULL AND expires_at>now() FOR UPDATE",[hash(r.body.token)]); const row=invite.rows[0]; if(row===undefined) { await client.query('ROLLBACK'); return reply.code(400).send({error:'Invalid or expired invitation.'}); } const user=await client.query<{email:string}>('SELECT email FROM users WHERE id=$1',[r.user.sub]); if(user.rows[0]?.email!==row.email) { await client.query('ROLLBACK'); return reply.code(403).send({error:'Invitation email does not match account.'}); } await client.query("INSERT INTO workspace_memberships(workspace_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=EXCLUDED.role",[row.workspace_id,r.user.sub,row.role]); await client.query('UPDATE workspace_invitations SET accepted_at=now() WHERE token_hash=$1',[hash(r.body.token)]); await client.query('COMMIT'); return {status:'accepted'}; } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }); }
function hash(value:string):string{return createHash('sha256').update(value).digest('hex');}
