import type { FastifyInstance } from "fastify";
import { Pool, type PoolConfig } from "pg";
import { requireWorkspaceRole } from "./rbac.js";
import type { IWorkflow } from "@spiderz/shared";
interface Params { readonly workspaceId: string; readonly workflowId?: string; }
export function registerWorkflowRoutes(app: FastifyInstance, config: PoolConfig): void { const pool = new Pool(config);
  app.post<{ Params: Params; Body: IWorkflow }>("/api/workspaces/:workspaceId/workflows", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member") }, async (request, reply) => { const workflow = request.body; if (workflow.name.trim() === "" || workflow.id.trim() === "") return reply.code(400).send({ error: "Workflow id and name are required." }); await pool.query("INSERT INTO workflows(id,owner_id,workspace_id,name,definition,environment) VALUES($1,$2,$3,$4,$5::jsonb,'development')", [workflow.id, request.user.sub, request.params.workspaceId, workflow.name, JSON.stringify(workflow)]); return reply.code(201).send(workflow); });
  app.get<{ Params: Params; Querystring: { q?: string } }>("/api/workspaces/:workspaceId/workflows", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member", "read_only") }, async (request) => { const q = request.query.q?.trim() ?? ""; const result = await pool.query<{ id: string; name: string; enabled: boolean; updated_at: Date; environment: string }>("SELECT id,name,enabled,updated_at,environment FROM workflows WHERE workspace_id=$1 AND name ILIKE $2 ORDER BY updated_at DESC LIMIT 100", [request.params.workspaceId, `%${q}%`]); return result.rows; });
  app.get<{ Params: Required<Params> }>("/api/workspaces/:workspaceId/workflows/:workflowId", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member", "read_only") }, async (request, reply) => { const result = await pool.query<{ definition: IWorkflow }>("SELECT definition FROM workflows WHERE id=$1 AND workspace_id=$2", [request.params.workflowId, request.params.workspaceId]); const workflow = result.rows[0]?.definition; return workflow === undefined ? reply.code(404).send({ error: "Workflow not found." }) : workflow; });
  app.put<{ Params: Required<Params>; Body: IWorkflow }>("/api/workspaces/:workspaceId/workflows/:workflowId", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member") }, async (request, reply) => { if (request.body.id !== request.params.workflowId) return reply.code(400).send({ error: "Workflow ID cannot change." }); const client = await pool.connect(); try { await client.query("BEGIN"); const updated = await client.query("UPDATE workflows SET name=$3,definition=$4::jsonb,version=version+1,updated_at=now() WHERE id=$1 AND workspace_id=$2 RETURNING version", [request.params.workflowId, request.params.workspaceId, request.body.name, JSON.stringify(request.body)]); if (updated.rowCount === 0) { await client.query("ROLLBACK"); return reply.code(404).send({ error: "Workflow not found." }); } await client.query("INSERT INTO workflow_versions(workflow_id,version_number,definition,created_by) VALUES($1,$2,$3::jsonb,$4)", [request.params.workflowId, updated.rows[0]?.version, JSON.stringify(request.body), request.user.sub]); await client.query("COMMIT"); return request.body; } catch (e: unknown) { await client.query("ROLLBACK"); throw e; } finally { client.release(); } });
  app.delete<{ Params: Required<Params> }>("/api/workspaces/:workspaceId/workflows/:workflowId", { preHandler: requireWorkspaceRole(config, "owner", "admin") }, async (request, reply) => { const result = await pool.query("DELETE FROM workflows WHERE id=$1 AND workspace_id=$2", [request.params.workflowId, request.params.workspaceId]); return result.rowCount === 0 ? reply.code(404).send({ error: "Workflow not found." }) : reply.code(204).send(); });
  app.get<{ Params: Required<Params> }>("/api/workspaces/:workspaceId/workflows/:workflowId/versions", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member", "read_only") }, async (r) => (await pool.query("SELECT id,version_number,created_at,immutable FROM workflow_versions WHERE workflow_id=$1 ORDER BY version_number DESC", [r.params.workflowId])).rows);
  app.get<{ Params: Required<Params> & { versionId: string } }>("/api/workspaces/:workspaceId/workflows/:workflowId/versions/:versionId", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member", "read_only") }, async (r, reply) => { const result = await pool.query<{ definition: IWorkflow }>("SELECT definition FROM workflow_versions WHERE id=$1 AND workflow_id=$2", [r.params.versionId, r.params.workflowId]); return result.rows[0] === undefined ? reply.code(404).send({ error: "Version not found." }) : result.rows[0].definition; });
  app.post<{ Params: Required<Params> & { versionId: string } }>("/api/workspaces/:workspaceId/workflows/:workflowId/versions/:versionId/restore", { preHandler: requireWorkspaceRole(config, "owner", "admin", "member") }, async (r, reply) => { const client=await pool.connect(); try { await client.query('BEGIN'); const v=await client.query<{definition:IWorkflow}>("SELECT v.definition FROM workflow_versions v JOIN workflows w ON w.id=v.workflow_id WHERE v.id=$1 AND v.workflow_id=$2 AND w.workspace_id=$3 AND w.environment='development'",[r.params.versionId,r.params.workflowId,r.params.workspaceId]); if(v.rows[0]===undefined){await client.query('ROLLBACK');return reply.code(404).send({error:"Development version not found."});} const updated=await client.query<{version:number}>("UPDATE workflows SET definition=$2::jsonb,version=version+1,updated_at=now() WHERE id=$1 RETURNING version",[r.params.workflowId,JSON.stringify(v.rows[0].definition)]); await client.query("INSERT INTO workflow_versions(workflow_id,version_number,definition,created_by,restore_message) VALUES($1,$2,$3::jsonb,$4,$5)",[r.params.workflowId,updated.rows[0]?.version,JSON.stringify(v.rows[0].definition),r.user.sub,`Restored from ${r.params.versionId}`]); await client.query("INSERT INTO audit_logs(workspace_id,actor_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'workflow.restore','workflow',$3,$4::jsonb)",[r.params.workspaceId,r.user.sub,r.params.workflowId,JSON.stringify({sourceVersionId:r.params.versionId})]); await client.query('COMMIT');return v.rows[0].definition;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();} }); }
