import type { JsonValue } from "@spiderz/shared";
import { WorkflowNodeExecutor, type INodeExecutionContext } from "@spiderz/core";

/** Uploads text generated by workflow items to Google Drive using an existing Google OAuth credential. */
export class GoogleDriveCreateTextFileExecutor extends WorkflowNodeExecutor {
  public async execute(context: INodeExecutionContext): Promise<readonly JsonValue[]> {
    const credentialId = Object.values(context.node.credentials)[0], fileName = context.node.parameters.fileName, contentField = context.node.parameters.contentField, folderId = context.node.parameters.folderId;
    if (typeof credentialId !== "string" || context.getCredentialAccessToken === undefined) throw new Error("Google Drive requires a Google OAuth2 credential.");
    if (typeof fileName !== "string" || fileName.trim() === "") throw new Error("Google Drive requires a file name.");
    if (folderId !== undefined && typeof folderId !== "string") throw new Error("Google Drive folder ID must be text.");
    const token = await context.getCredentialAccessToken(credentialId);
    const output: JsonValue[] = [];
    for (const item of context.input) {
      const content = stringAtPath(item, typeof contentField === "string" ? contentField : "reply");
      const boundary = `spiderz-${crypto.randomUUID()}`;
      const metadata = JSON.stringify({ name: fileName, mimeType: "text/plain", ...(typeof folderId === "string" && folderId.trim() !== "" ? { parents: [folderId] } : {}) });
      const body = `--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${content}\r\n--${boundary}--`;
      const response = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart", { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": `multipart/related; boundary=${boundary}` }, body, signal: context.signal });
      const payload = await response.json().catch(() => undefined) as JsonValue;
      if (!response.ok) throw new Error(`Google Drive upload failed (${response.status}): ${googleError(payload)}.`);
      output.push(payload);
    }
    return output;
  }
}
function googleError(value: JsonValue): string { return typeof value === "object" && value !== null && !Array.isArray(value) && typeof value.error === "object" && value.error !== null && !Array.isArray(value.error) && typeof value.error.message === "string" ? value.error.message : "Google did not return an error message"; }
function stringAtPath(value: JsonValue, path: string): string { const result = path.split(".").reduce<JsonValue | undefined>((current, segment) => typeof current === "object" && current !== null && !Array.isArray(current) ? current[segment] : undefined, value); return result === undefined || result === null ? "" : typeof result === "object" ? JSON.stringify(result) : String(result); }
